### ISSUE TITLE
Error during webpack compile with UglifyJs

### ISSUE THREAD

**Issue by nuclearspike** [rotorz/markdown-it-external-links#2]
ERROR in main.015bf73eb5660571803b.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [../~/markdown-it-external-links/lib/index.js:17,0]

But line 17 is:

```
      ? options.internalDomains.map(domain => domain.toLowerCase())
```

Any ideas?

**Comment by nuclearspike** [comment]
After I wiped the node_modules dir and re-installed, the error went away. Sorry!

**Comment by nuclearspike** [comment]
Sorry for closing this. It is still an issue when doing a production build.

```
import MarkdownIt from 'markdown-it';
const md = new MarkdownIt({
  html: true,     
  xhtmlOut: true, // <br/>
  breaks: true,   // \n -> <br>
  linkify: false,
  typographer: false,
});

import externalLinks from 'markdown-it-external-links';

md.use(externalLinks, {
  externalClassName: 'external-link',
  externalTarget: '_blank',
  internalDomains: ['localhost', 'mydomain.com'],
});
```

I'm using 

```
markdown-it                       6.0.4
```

Even though the latest is 7 just to rule out version incompatibilities.

**Comment by kruncher** [comment]
The project is authored in ES6 so it might just be the case that you need to use Babel or Traceur to convert the source into ES5 first.

Let me know if this helps.

**Comment by nuclearspike** [comment]
It's a react app and uses Babel already.

**Comment by kruncher** [comment]
Make sure that you have enabled the es2015 transform preset; then this should compile:

http://babeljs.io/docs/plugins/preset-es2015/

**Comment by nuclearspike** [comment]
It was already using es2015.

It did compile but ugly js gave errors. The bundle works on my laptop but
fails to load on iPad.

**Comment by kruncher** [comment]
It seems that you are somehow providing the non-es2015 processed version of the scripts to ugly js; since your babel pipeline should be substituting the arrow functions with the ES5 function syntax.

**Comment by nuclearspike** [comment]
The same issue persists. The following error creates a bundle that works on my laptop but not my iPad.

```
ERROR in main.2ee24c8b43dad2ddf9b0.js from UglifyJs
SyntaxError: Unexpected token: name (externalClassName) [../~/markdown-it-external-links/lib/index.js:10,0]
```

I use arrow functions all over my code, so that's not it.

```
const externalLinks = require('markdown-it-external-links');

md.use(externalLinks, {
  externalClassName: 'external-link',
  externalTarget: '_blank',
  internalDomains: ['localhost', 'www.lokaltravel.com'],
});
```
