### ISSUE TITLE
why not use rel=external?

### ISSUE THREAD

**Issue by xi** [rotorz/markdown-it-external-links#4]
There is a well-established `rel` value for this: [`external`](http://microformats.org/wiki/rel-external). This can be target by CSS using the `a[rel~="external"]` selector. It would be nice if this plugin would allow to use this. (I would even like to have it as default).

**Comment by kruncher** [comment]
I do not want to change the default behaviour but I am happy to merge the opt-in functionality that is provided by the following pull request:

https://github.com/rotorz/markdown-it-external-links/pull/1

Many thanks!
