### ISSUE TITLE
let is not valid ES5

### ISSUE THREAD

**Issue by timfish** [rotorz/markdown-it-external-links#6]
Thanks for markdown-it module I've been using it for a while.

Just a minor issue, when I came to minify my app with uglify-js, it trips up on the usages of `let` as uglify-js can only cope with ES5. I'm pretty sure [most browsers](http://caniuse.com/#feat=let) worth considering support `let` but uglify-js certainly appears not to!

**Comment by kruncher** [comment]
If you want to use this with ES5 you will need to use the likes of Babel to transform.

When using with a browser I suspect that you want to be using something like Browserify to combine your common scripts into a single script. You can use babel in this workflow to turn ES6 into ES5.
